name-template: 'v$NEXT_MAJOR_VERSION.$NEXT_MINOR_VERSION.$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_MAJOR_VERSION.$NEXT_MINOR_VERSION.$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels: [feature]
  - title: '🐛 Bug Fixes'
    labels: [bug]
  - title: '📝 Documentation'
    labels: [documentation]
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-resolver:
  major: { 'pattern': 'BREAKING CHANGE' }
  minor: { 'pattern': 'feat' }
  patch: { 'pattern': 'fix' }
template: |
  ## Changes
  $CHANGES
no-changes-template: '* No changes'
