ARCGIS_BASE_URL: str = "https://services.arcgis.com"

ARCGIS_LAND_DATASET_PATH: str = "/fLeGjb7u4uXqeF9q/ArcGIS/rest/services/Vacant_Indicators_Land/FeatureServer/0/query"
ARCGIS_BUILDINGS_DATASET_PATH: str = "/fLeGjb7u4uXqeF9q/ArcGIS/rest/services/Vacant_Indicators_Bldg/FeatureServer/0/query"
ARCGIS_PHS_LANDCARE_DATASET_PATH: str = (
    "/fLeGjb7u4uXqeF9q/ArcGIS/rest/services/PHS_CommunityLandcare/FeatureServer/0/query"
)
ARCGIS_PHS_MAINTENANCE_DATASET_PATH: str = "/fLeGjb7u4uXqeF9q/ArcGIS/rest/services/PHS_PhilaLandCare_Maintenance/FeatureServer/0/query"
ARCGIS_COMMUNITY_ORGANISATIONS_DATASET_PATH: str = (
    "/fLeGjb7u4uXqeF9q/ArcGIS/rest/services/Zoning_RCO/FeatureServer/0/query"
)

PHILADELPHIA_CARTO_BASE_URL: str = "https://phl.carto.com/api/v2/sql"

PHILADELPHIA_NEIGHBORHOODS_DATASET_URL: str = "https://github.com/azavea/geo-data/raw/master/Neighborhoods_Philadelphia/Neighborhoods_Philadelphia.zip"

PHILADELPHIA_TREE_CANOPY_DATASET_URL: str = (
    "https://national-tes-data-share.s3.amazonaws.com/national_tes_share/pa.zip.zip"
)

DEFAULT_ARCGIS_QUERY_PARAMETERS: dict = {
    "where": "1=1",
    "outFields": "*",
    "returnGeometry": "true",
    "f": "json",
    "resultRecordCount": 2000,
}

PUBLIC_PROPERTY_OWNER_VALUES = [
    "PHILADELPHIA HOUSING DEVELOPMENT CORPORATION",
    "REDEVELOPMENT AUTHORITY OF PHILADELPHIA",
    "PHILA REDEVELOPMENT AUTHO",
    "COMMONWEALTH OF PENNA",
    "DEPT OF PUBLIC PROP; CITY OF PHILA",
    "PHILA HOUSING AUTHORITY",
    "PHILADELPHIA HOUSING AUTH",
    "PUBLIC PROP DIV; CITY OF PHILA",
    "COMMONWEALTH OF PA",
    "REAL ESTATE DIV; CITY OF PHILA",
    "PHILADELPHIA HOUSING AUTHORITY",
    "PHILADELPHIA REDEVELOPMENT AUTH",
    "DEVELOPMENT CORPORATION; PHILADELPHIA HOUSING",
    "DEPT OF PUB PROP; CITY OF PHILA",
    "URBAN DEVELOPMENT; SECRETARY OF HOUSINGURBAN DEVELOPMENT; SECRETARY OF HOUSING AND",
    "PHILADELPHIA LAND BANK",
    "PUBLIC PROP REAL ESTATE; CITY OF PHILA",
    "PENNDOT",
    "REAL ESTATE DIVISION; CITY OF PHILA",
    "PHILADELPHIA LAND INVESTM",
    "DEPT OF PUBLIC PROP; CITY OF PHILADELPHIA",
    "REDEVELOPMENT AUTHORITY OF PHILA",
    "CITY OF PHILADELPHIA DEPARTMENT OF PUBLIC PROPERTY",
    "DEPT OF PUBLC PROP; CITY OF PHILA",
    "PHILA HOUSING DEV CORP",
    "PHILA REDEVELOPMENT AUTH",
    "KENSINGTON HOUSING AUTHOR",
    "REDEVELOPMENT AUTHORITY O",
    "PHILADELPHIA LAND INVESTMENT",
    "PHILADELPHIA REDEVELOPMEN",
    "COMMONWEALTH OF PENNSYLVANIA",
    "DEP OF PUB PROP; CITY OF PHILA",
    "SECRETARY OF HOUSING AND URBAN DEVELOPMENT",
    "PHILADELPHIA REDEVELOPMENT AUTHORITY",
    "CITY OF PHILADELPHIA",
    "KENSINGTON HOUSING AUTHORITY",
    "DEPT PUBLIC PROP R E DIV; CITY OF PHILA",
    "REDEVELOPMENT AUTHORITY",
    "CITY OF PHILA",
    "DEPT PUB PROP; CITY OF PHILA",
]

REDEVELOPMENT_OWNER_VALUES = [
    "REDEVELOPMENT AUTHORITY OF PHILA",
    "PHILA REDEVELOPMENT AUTH",
    "REDEVELOPMENT AUTHORITY O",
    "PHILADELPHIA REDEVELOPMEN",
    "PHILA REDEVELOPMENT AUTHO",
    "REDEVELOPMENT AUTHORITY",
    "REDEVELOPMENT AUTH",
]

DEPARTMENT_OF_PUBLIC_PROPERTY_OWNER_VALUES = [
    "DEPT OF PUBLIC PROPERTY",
    "DEPT OF PUBLIC PROPERT",
    "DEPT OF PUBLC PROP; CITY OF " "PHILA",
    "DEPT OF PUBLIC PROP; CITY OF PHILA",
    "DEPT OF PUBLIC PROPERTY; CITY OF PHILA",
    "DEPT PUB PROP; CITY OF PHILA",
    "DEPT OF PUB PROP; CITY OF PHILA",
    "DEP OF PUB PROP; CITY OF PHILA",
    "DEPT OF PUBLIC PROP; CITY OF PHILADELPHIA",
    "DEPT PUBLIC PROP R E DIV; CITY OF PHILA",
    "PUBLIC PROP DIV; CITY OF PHILA",
    "PUBLIC PROP REAL ESTATE; CITY OF PHILA",
    "REAL ESTATE DIV; CITY OF PHILA",
    "REAL ESTATE DIVISION; CITY OF PHILA",
]
