export const neighborhoods: string[] = [
  'Academy Gardens',
  'Airport',
  'Allegheny West',
  'Andorra',
  'Aston-Woodbridge',
  'Bartram Village',
  'Bella Vista',
  'Belmont',
  'Brewerytown',
  'Bridesburg',
  'Burholme',
  'Bustleton',
  'Byberry',
  'Callowhill',
  'Carroll Park',
  'Cedar Park',
  'Cedarbrook',
  'Center City East',
  'Chestnut Hill',
  'Chinatown',
  'Clearview',
  'Cobbs Creek',
  'Crescentville',
  'Crestmont Farms',
  'Dearnley Park',
  'Dickinson Narrows',
  'Dunlap',
  'East Falls',
  'East Germantown',
  'East Kensington',
  'East Mount Airy',
  'East Oak Lane',
  'East Park',
  'East Parkside',
  'East Passyunk',
  'East Poplar',
  'Eastwick',
  'Elmwood',
  'Fairhill',
  'Fairmount',
  'Feltonville',
  'Fern Rock',
  'Fishtown - Lower Kensington',
  'Fitler Square',
  'Fox Chase',
  'Francisville',
  'Frankford',
  'Franklin Mills',
  'Franklinville',
  'Garden Court',
  'Germantown - Morton',
  'Germantown - Penn Knox',
  'Germantown - Westside',
  'Germany Hill',
  'Girard Estates',
  'Glenwood',
  'Graduate Hospital',
  'Grays Ferry',
  'Greenwich',
  'Haddington',
  'Harrowgate',
  'Hartranft',
  'Haverford North',
  'Hawthorne',
  'Holmesburg',
  'Hunting Park',
  'Industrial',
  'Juniata Park',
  'Kingsessing',
  'Lawndale',
  'Lexington Park',
  'Logan',
  'Logan Square',
  'Lower Moyamensing',
  'Ludlow',
  'Manayunk',
  'Mantua',
  'Mayfair',
  'McGuire',
  'Mechanicsville',
  'Melrose Park Gardens',
  'Mill Creek',
  'Millbrook',
  'Modena',
  'Morrell Park',
  'Navy Yard',
  'Newbold',
  'Nicetown',
  'Normandy Village',
  'North Central',
  'Northeast Phila Airport',
  'Northern Liberties',
  'Northwood',
  'Ogontz',
  'Old City',
  'Old Kensington',
  'Olney',
  'Overbrook',
  'Oxford Circle',
  'Packer Park',
  'Parkwood Manor',
  'Paschall',
  'Passyunk Square',
  'Pennsport',
  'Pennypack',
  'Pennypack Park',
  'Pennypack Woods',
  'Penrose',
  'Point Breeze',
  'Port Richmond',
  'Powelton',
  'Queen Village',
  'Rhawnhurst',
  'Richmond',
  'Rittenhouse',
  'Riverfront',
  'Roxborough',
  'Roxborough Park',
  'Sharswood',
  'Society Hill',
  'Somerton',
  'Southwest Germantown',
  'Southwest Schuylkill',
  'Spring Garden',
  'Spruce Hill',
  'Stadium District',
  'Stanton',
  'Strawberry Mansion',
  'Summerdale',
  'Tacony',
  'Tioga',
  'Torresdale',
  'University City',
  'Upper Kensington',
  'Upper Roxborough',
  'Walnut Hill',
  'Washington Square West',
  'West Central Germantown',
  'West Kensington',
  'West Mount Airy',
  'West Oak Lane',
  'West Park',
  'West Parkside',
  'West Passyunk',
  'West Poplar',
  'West Powelton',
  'West Torresdale',
  'Whitman',
  'Winchester Park',
  'Wissahickon',
  'Wissahickon Hills',
  'Wissahickon Park',
  'Wissinoming',
  'Wister',
  'Woodland Terrace',
  'Wynnefield',
  'Wynnefield Heights',
  'Yorktown',
];

export const rcos: string[] = [
  '10th Democratic Ward',
  '12th Ward Democratic Committee',
  '12th and Cambria Advisory Board',
  '13th Democratic Ward',
  '14th Community Organization',
  '1st Ward Republicans',
  '21st Ward Democratic Committee',
  '22nd Ward Democratic RCO',
  '24th Ward Republican RCO',
  '26th Republican Ward',
  '27th Republican Ward',
  '35th Democratic Ward',
  '37th Ward Executive Democratic Committee',
  '3rd Ward Executive Committee',
  '3rd Ward Republicans',
  '40th Ward Republicans',
  '42nd Democratic Ward',
  '44th Democratic Ward',
  '44th Ward Republican',
  '46th Republican Ward',
  '46th Ward Democratic Committee',
  '50th Democratic Ward',
  '51st Republican Ward',
  '51st Ward Democratic Executive Committee',
  '52nd Democratic Ward',
  '53rd Republican Ward',
  '59th Democratic Ward',
  'A Concerned Community Association (ACCA)',
  'ACANA CDC- United Southwest Neighbors',
  'ACHIEVEability',
  'All In The Family Group Associates Incorporated',
  'Allegheny West Civic Association',
  'Arbours at Eagle Pointe Community Association',
  'Asian American Federation of the United States',
  'Asociacion Puertorriquenos En Marcha (APM)',
  'Awbury Arboretum Neighbors',
  'Baynton Hill Neighbors',
  'Beech Community Services Incorporated',
  'Bella Vista Neighbors Association',
  'Belmont Alliance Civic Association CDC',
  'Blue Bell Hill Civic Association',
  'Brewerytown Sharswood Community Civic Association',
  'Bridesburg Community Action Alliance',
  'Broad Street West Civic Association',
  'Burholme Community Town Watch and Civic Association',
  'Bustleton Neighbors Association',
  'Callowhill Neighborhood Association',
  'Cathedral Park Community Development Association',
  'Cedar Park Neighbors',
  'Cedar Point Park Neighborhood Association',
  'Celestial Community Development Corporation',
  'Centennial Parkside Community Development Corporation',
  'Center City Organized for Responsible Development',
  'Center City Residents Association (CCRA)',
  'Central Delaware Advocacy Group (CDAG)',
  'Central Manayunk Council',
  'Central Roxborough Civic Association (CRCA)',
  'Chestnut Hill Business Improvement District',
  'Chestnut Hill Community Association',
  'Chestnut Hill Conservancy',
  'Chew and Belfield Neighbors Club Incorporated',
  'City Avenue Special Services District of Philadelphia and Lower Merion',
  'Cliveden Hills Association',
  'Cobbs Creek Neighbors Association',
  'Cobbs Creek Watershed RCO',
  'Community Action Group',
  'Community on the Rise',
  'Concerned Citizens of Point Breeze',
  'Concerned Neighbors for Change',
  'Dickinson Square West Civic Association',
  'Drexel Area Property Association',
  'East Falls Community Council',
  'East Kensington Neighbors Association',
  'East Mt. Airy Neighbors',
  'East Parkside Residential Association',
  'East Passyunk Crossing Civic Association (EPX)',
  'East Point Breeze Neighbors',
  'East Torresdale Civic Association',
  'Eastwick Community Network',
  'Eastwick Friends & Neighbors Coalition',
  'Eastwick United CDC',
  'Empowered Community Development Corporation',
  'Fairmount Civic Association',
  'Faith Community Development Corporation (FCDC)',
  'Fishtown Kensington Area Business Improvement District',
  'Fishtown Neighbors Association',
  'Fitler Square Neighborhood Association',
  'Fox Chase Civic Association',
  'Foxx Lane RCO',
  'Frankford CDC',
  'Frankford Kensington Development Council',
  'Franklin Bridge North Neighbors Inc',
  'Friends of Clark Park',
  'Friends of Historic FDR Park',
  'Friends of Ogden Park',
  'Friends of Penrose',
  'Friends of the Wissahickon',
  'Garden Court Community Association',
  'Girard Estate Area Residents (GEAR)',
  'Girard Estate Neighbors Association',
  'Grays Ferry Coalition of Neighbors',
  'Grays Ferry Community Council',
  'Greater Bustleton Civic League',
  'Greenhill Farms Civic Assn.',
  'HACE CDC',
  'HMC Squared Community Association, INC',
  'Harrowgate Civic Association',
  'Hawthorne Empowerment Coalition',
  'Helping Unite Belmont',
  'Holly Street Neighbors CDC',
  'Holme Circle Civic Association',
  'Holmesburg Civic Association',
  'Hunting Park Connected',
  'Impact Community Development Corporation',
  'Jayhawks Community Association',
  'Juniata Park Civic Association',
  'KECO INC',
  'Kensington Independent Civic Association',
  'Kensington Neighborhood Association',
  'Kingsessing Area Civic Association',
  'Lancaster Avenue 21st Century Business Association',
  'Lawncrest Community Association',
  'Logan Civic Association',
  'Logan Community Enterprise Center, Inc.',
  'Logan Square Neighborhood Association',
  'Lower Moyamensing Civic Association',
  'MAP Holistic CDC',
  'Make it Happen Philly',
  'Manayunk Neighborhood Council',
  'Mantua Civic Association',
  'Mayfair Business Improvement District (BID)',
  'Mayfair Civic Association',
  'Mechanicsville Civic Association',
  'Mill Creek Advisory Council',
  'Millbrook Civic Association',
  'Mt. Airy Business Improvement District',
  'Neighbors of Overbrook Association (NOAH)',
  'New Kensington Community Development Corp',
  'Nicetown CDC',
  'Nicetown-Tioga Improvement Team',
  'Normandy Civic Association',
  'Norris Square Community Action Network-NSCAN',
  'Norris Square Community Alliance',
  'North Central East RCO',
  'North Central Philadelphia Susquehanna Community Development Corporation',
  'North Penn Community Action Council',
  'North of Washington Avenue Coalition',
  'Northeast Community Civic Alliance',
  'Northeast Philadelphia Development Corporation',
  'Northern Liberties Neighbors Association',
  'Northwood Civic Association',
  'Nueva Esperanza Housing and Economic Development',
  'Oak Lane Community Action Association',
  'Oak Lane/Wister Community Coalition',
  'Old City District',
  'Olde Kensington Neighborhood Association',
  'Olde Richmond Civic Association',
  "Original Morrocco's of Francisville inc.",
  'Overbrook Farms Club',
  'Overbrook Park Civic Association',
  'Overbrook West Neighbors, Inc.',
  'Packer Park Civic Association',
  'Parkside Association',
  'Parkwood Area Civic Association',
  'Paschall Betterment League, Inc',
  'Passyunk Square Civic Association',
  'Penn Knox Neighborhood Association',
  'Pennsport Civic Association',
  "People's Emergency Center Community Development Corporation",
  'Philadelphia Chinatown Development Corporation',
  'Philadelphia Chinese Chamber of Commerce',
  'Philly Foot Forward',
  'Philly Thrive (SWPDC)',
  'Point Breeze Community Development Coalition',
  'Point Breeze Network Plus',
  'Pomona Cherokee Civic Council (PCCC) RCO',
  'Port Richmond Industrial Development Enterprise (PRIDE)',
  'Port Richmond On Patrol & Civic Association (PROPAC)',
  'Powelton Village Civic Association',
  'Price-Knox Neighbors Assn.',
  'Queen Village Neighbors Association',
  'RAH Civic Association',
  'Residents Organized for Advocacy and Direction',
  'Residents of Shawmont Valley Association',
  'Rhawnhurst Civic Association',
  'Ridge Park Civic Association',
  "River's Edge Community Association",
  'Roxborough Development Corporation',
  'SoLo/Germantown Civic Association',
  'Society Hill Civic Association',
  'Somerset Neighbors for Better Living',
  'Somerton Civic Association',
  'South Broad Street Neighborhood Association',
  'South Kensington Community Partners',
  'South Philadelphia Communities Civic Association (SPCCA)',
  'South Port Richmond Civic Association',
  'South Street Headhouse District',
  'South Street West Improvement District, Inc',
  'South of South Neighborhood Association (SOSNA)',
  'Southwest Philadelphia District Services (SWPDS)',
  'Spring Garden Civic Association',
  'Spruce Hill Community Association',
  "St. Elizabeth's RCO",
  'Strawberry Mansion Community Concern',
  'Strawberry Mansion Community Development Corporation',
  'Swampoodle Neighborhood Parcels Association',
  'Tacony Civic Association',
  'Take Back Your Neighborhood',
  'Tasker-Morris Neighbors Association',
  'Temple Area Property Association (TAPA)',
  'The Generationals of Philadelphia - Cobbs Creek',
  'The Good News Community Organization',
  'Tioga United, Inc.',
  'United Francisville Civic Association',
  'United Neighbors Alliance Civic Association',
  'Upper Holmesburg Civic Association',
  'Upper North Coalition of Community Councils',
  'Upper North Neighbors Association',
  'Upper Roxborough Civic Association',
  'Uptown Entertainment and Development Corporation',
  'Veterans Stadium Neighbors Civic Association',
  'Viola Street Residents Association',
  'Wakefield 49ers Community Development and Improvement Association',
  'Walnut Hill Community Association',
  'Walton Park Civic Assn (WALPAC)',
  'Washington Avenue Association of Businesses and Residents',
  'Washington Avenue Property Owners Association',
  'Washington Square West Civic Association',
  'West Belmont Civic Association',
  'West Central Germantown Neighbors',
  'West Chelten Neighbors Association',
  'West Girard Progress',
  'West Mount Airy Neighbors, Inc.',
  'West Passyunk Neighbors Association (WPNA)',
  'West Philadelphia Economic Development Council',
  'West Philly Plan + Preserve',
  'West Philly Together',
  'West Philly United Neighbors',
  'West Powelton Saunders Park RCO',
  'West Torresdale/Morrell Park Civic Association',
  'Whitman Council Incorporated',
  'Winchester Park Civic Association',
  'Wissahickon Interested Citizens Association',
  'Wissahickon Neighbors Civic Association (WNCA)',
  'Wissinoming Civic Association',
  'Wissinoming Neighborhood Affirmative Action Group',
  'Woodland Terrace HomeOwners Association',
  'Wynnefield Community Neighborhood Association',
  'Wynnefield Heights Civic Association',
  'Wynnefield Residents Association',
  'Yorktown Community Development Corporation',
];

export const zoning: string[] = [
  'CA',
  'CMX',
  'I',
  'ICMX',
  'IRMX',
  'RM',
  'RMX',
  'RSA',
  'RSD',
  'RTA',
  'SP',
];

export const subZoning: Record<string, string[]> = {
  CA: ['CA-1', 'CA-2'],
  CMX: ['CMX-1', 'CMX-2', 'CMX-2.5', 'CMX-3', 'CMX-4', 'CMX-5'],
  I: ['I-1', 'I-2', 'I-3', 'I-P'],
  ICMX: ['ICMX'],
  IRMX: ['IRMX'],
  RM: ['RM-1', 'RM-2', 'RM-3', 'RM-4'],
  RMX: ['RMX-1', 'RMX-2', 'RMX-3'],
  RSA: ['RSA-1', 'RSA-2', 'RSA-3', 'RSA-4', 'RSA-5', 'RSA-6'],
  RSD: ['RSD-1', 'RSD-2', 'RSD-3'],
  RTA: ['RTA-1'],
  SP: ['SP-AIR', 'SP-INS', 'SP-PO-A', 'SP-STA'],
};
