name: PR Checks

on:
  push:
    branches:
      - staging

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint
        continue-on-error: true

      - name: Run Prettier Check
        run: npm run format:check
        continue-on-error: true

      - name: Check linting and formatting
        if: failure()
        run: |
          echo "Linting or formatting issues found. Please run 'npm run lint:fix' and 'npm run format' to fix them."
          exit 1

      - name: Linting and formatting success
        if: success()
        run: echo "No linting or formatting issues found. Good job!"
